### ISSUE TITLE
Element rendering and styling issues

### ISSUE THREAD

**Issue by aneesazc** [aneesazc/NxtJob-Community-App#4]
An element in the navbar that should show the page title does not render. It it is set to hidden in small screen sizes but it stays hidden always. There is also issue with bg color not appearing and heights not changing for the cards in the home page

**Comment by StefanG1102** [comment]
hey. I would like to Help you there, i have some question. At the moment it looks like this 
![image](https://github.com/aneesazc/NxtJob-Community-App/assets/166592974/ae8a0e1a-e74f-4883-9974-f7935e77cb5b) is this right ? and you want this element to be shown 
![image](https://github.com/aneesazc/NxtJob-Community-App/assets/166592974/fd6c5d6a-93d7-4643-83a1-164603c1c817) or is there some other element ?

**Comment by aneesazc** [comment]
Hi, yes exactly, I tried to remove the hidden styles and bg color still did not appear. If you can make it appear that would be great, let me know if you want to!

**Comment by StefanG1102** [comment]
yes i would like a try on that

**Comment by aneesazc** [comment]
do a git pull before making a PR and good luck
